name: github-actions-workflow
on:
  push:
    branches:
      - "*"
    exclude:
      - main
jobs:
  check-main-branch:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: PRINT MESSAGE
        run: echo "you are not allowed to push to main branch" exit 1