name: github-actions-workflow
on:
  push:
    branches:
      - "*"
    exclude:
      - main
jobs:
  check-main-branch:
    runs-on: ubuntu-latest
    if:
      - $GITHUB_REF = "refs/heads/main"
    steps:
      - name: PRINT MESSAGE
      - uses: thakkarchintan411/github-actions
      - run: echo "you are not allowed to push to main branch"