name: github-actions-workflow

on:
  push:
    branches:
      - '*'
    exclude:
      - main

jobs: 
  check-main-branch:
    runs-on: ubuntu-latest
     run: |
          if [ $GITHUB_REF = "refs/heads/main" ]; then
            echo "Pushing to the main branch is not allowed."
            exit 1
          fi 