name: github-actions-workflow
on:
  push:
    branches:
      - "*"
    exclude:
      - main
jobs:
  check-main-branch:
    runs-on: ubuntu-latest
    if:
      - $GITHUB_REF = "refs/heads/main"
    steps: echo "you are not allowed to push to main branch"
